### ISSUE TITLE
iptables --wait option not supported in some linux flavors

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry-incubator/guardian#39]
Concourse web+worker 1.3.1 running on standard AWS AMI.

With the simple hello world concourse demo, every run gives me this immediately:

Snippet:

`errors.errorString{s:\\\"iptables create-instance-chains: iptables v1.4.18: unknown option \\\\\\\"--wait\\\\\\\"\\\\nTry 'iptables -h' or 'iptables --help' for more information.`

This might be a guardian thing - I'm seeing cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:44 in the log.

Full:

```
runc start: exit status 1: process_linux.go:329: running prestart hook 0 caused "exit status 2: {\"timestamp\":\"1466369914.619743586\",\"source\":\"kawasaki\",\"message\":\"kawasaki.hook.start\",\"log_level\":1,\"data\":{\"config\":{\"HostIntf\":\"wmcnismvpm14-0\",\"ContainerIntf\":\"wmcnismvpm14-1\",\"IPTablePrefix\":\"w--\",\"IPTableInstance\":\"mcnismvpm14\",\"BridgeName\":\"wbrdg-0afe0000\",\"BridgeIP\":\"10.254.0.1\",\"ContainerIP\":\"10.254.0.2\",\"ExternalIP\":\"172.31.30.19\",\"Subnet\":{\"IP\":\"10.254.0.0\",\"Mask\":\"/////A==\"},\"Mtu\":1500,\"DNSServers\":null},\"pid\":908,\"session\":\"1\"}}\n{\"timestamp\":\"1466369914.773725510\",\"source\":\"kawasaki\",\"message\":\"kawasaki.hook.panicked\",\"log_level\":3,\"data\":{\"config\":{\"HostIntf\":\"wmcnismvpm14-0\",\"ContainerIntf\":\"wmcnismvpm14-1\",\"IPTablePrefix\":\"w--\",\"IPTableInstance\":\"mcnismvpm14\",\"BridgeName\":\"wbrdg-0afe0000\",\"BridgeIP\":\"10.254.0.1\",\"ContainerIP\":\"10.254.0.2\",\"ExternalIP\":\"172.31.30.19\",\"Subnet\":{\"IP\":\"10.254.0.0\",\"Mask\":\"/////A==\"},\"Mtu\":1500,\"DNSServers\":null},\"error\":\"\\u0026errors.errorString{s:\\\"iptables create-instance-chains: iptables v1.4.18: unknown option \\\\\\\"--wait\\\\\\\"\\\\nTry `iptables -h' or 'iptables --help' for more information.\\\\n\\\"}\",\"pid\":908,\"session\":\"1\",\"trace\":\"goroutine 1 [running]:\\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc82000f5c0, 0x97e0e0, 0x8, 0x7f2251de0028, 0xc8201e1950, 0x0, 0x0, 0x0)\\n\\t/tmp/build/9674af12/garden-runc-release/src/github.com/pivotal-golang/lager/logger.go:131 +0xc5\\nmain.main.func1(0xc820199c08)\\n\\t/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:44 +0x13c\\npanic(0x8a3540, 0xc8201e1920)\\n\\t/usr/local/go/src/runtime/panic.go:443 +0x4e9\\nmain.main()\\n\\t/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:92 +0x171b\\n\"}}\npanic: iptables create-instance-chains: iptables v1.4.18: unknown option \"--wait\"\nTry `iptables -h' or 'iptables --help' for more information.\n [recovered]\n\tpanic: &errors.errorString{s:\"iptables create-instance-chains: iptables v1.4.18: unknown option \\\"--wait\\\"\\nTry `iptables -h' or 'iptables --help' for more information.\\n\"}\n\ngoroutine 1 [running]:\npanic(0x8a3540, 0xc8201e1950)\n\t/usr/local/go/src/runtime/panic.go:481 +0x3e6\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc82000f5c0, 0x97e0e0, 0x8, 0x7f2251de0028, 0xc8201e1950, 0x0, 0x0, 0x0)\n\t/tmp/build/9674af12/garden-runc-release/src/github.com/pivotal-golang/lager/logger.go:152 +0x698\nmain.main.func1(0xc820199c08)\n\t/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:44 +0x13c\npanic(0x8a3540, 0xc8201e1920)\n\t/usr/local/go/src/runtime/panic.go:443 +0x4e9\nmain.main()\n\t/tmp/build/9674af12/garden-runc-release/src/github.com/cloudfoundry-incubator/guardian/cmd/kawasaki/main.go:92 +0x171b\n"
```

**Comment by jadekler** [comment]
Not sure if this is a guardian 'issue' since guardian-release states it only supports ubuntu 14.04 ([which has its own problems](https://github.com/cloudfoundry-incubator/guardian/issues/38)), so feel free to close if not.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#121887289](https://www.pivotaltracker.com/story/show/121887289) iptables --wait option not supported in some linux flavors


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by goonzoid** [comment]
Hi @jadekler, thanks for raising this. This is caused by guardian trying to use an incompatible version of iptables. We've recently made it so that the path to the iptables binary can be configured, so the solution is to use that, along with a compatible version of iptables. I think the concourse folks will include a fix for this soon.

cc @vito

**Comment by jadekler** [comment]
Great! Thanks @goonzoid
