### ISSUE TITLE
run ginkgo test error

### ISSUE THREAD

**Issue by AdoHe** [cloudfoundry-incubator/guardian#4]
Hi guys, I try to run the ginkgo tests, but just failed, and the error log is:
```
Running Suite: Gqt Suite
========================
Random Seed: 1445845654
Will run 1 of 1 specs

[d][guardian] spawned /tmp/gexec_artifacts826867777/g190076076/guardian (pid: 25141)
[o][guardian] {"timestamp":"1445845659.613978386","source":"guardian","message":"guardian.runner.command.starting","log_level":0,"data":{"argv":["mountpoint","-q","/tmp/cgroups-1"],"session":"2.1"}}
[o][guardian] {"timestamp":"1445845659.615394592","source":"guardian","message":"guardian.runner.command.failed","log_level":2,"data":{"argv":["mountpoint","-q","/tmp/cgroups-1"],"error":"exit status 1","exit-status":1,"session":"2.1","stderr":"","stdout":"","took":"1.406194ms"}}
[o][guardian] {"timestamp":"1445845659.615459681","source":"guardian","message":"guardian.runner.command.starting","log_level":0,"data":{"argv":["mount","-t","tmpfs","-o","uid=0,gid=0,mode=0755","cgroup","/tmp/cgroups-1"],"session":"2.2"}}
[o][guardian] {"timestamp":"1445845659.621389866","source":"guardian","message":"guardian.runner.command.succeeded","log_level":0,"data":{"argv":["mount","-t","tmpfs","-o","uid=0,gid=0,mode=0755","cgroup","/tmp/cgroups-1"],"exit-status":0,"session":"2.2","took":"5.922984ms"}}
[o][guardian] {"timestamp":"1445845659.621483088","source":"guardian","message":"guardian.setup-cgroup.started","log_level":1,"data":{"path":"/tmp/cgroups-1/cpu","session":"7","type":"cpu"}}
[o][guardian] {"timestamp":"1445845659.621526241","source":"guardian","message":"guardian.runner.command.starting","log_level":0,"data":{"argv":["mountpoint","-q","/tmp/cgroups-1/cpu"],"session":"2.3"}}
[o][guardian] {"timestamp":"1445845659.623045683","source":"guardian","message":"guardian.runner.command.failed","log_level":2,"data":{"argv":["mountpoint","-q","/tmp/cgroups-1/cpu"],"error":"exit status 1","exit-status":1,"session":"2.3","stderr":"","stdout":"","took":"1.508992ms"}}
[o][guardian] {"timestamp":"1445845659.623255491","source":"guardian","message":"guardian.runner.command.starting","log_level":0,"data":{"argv":["mount","-n","-t","cgroup","-o","cpu","cgroup","/tmp/cgroups-1/cpu"],"session":"2.4"}}
[o][guardian] {"timestamp":"1445845659.624535322","source":"guardian","message":"guardian.setup-cgroup.mount-cgroup-cmd.received-data","log_level":1,"data":{"data":"mount: cgroup is already mounted or /tmp/cgroups-1/cpu busy\n","path":"/tmp/cgroups-1/cpu","session":"7.1","type":"cpu"}}
[o][guardian] {"timestamp":"1445845659.624782324","source":"guardian","message":"guardian.setup-cgroup.mount-cgroup-cmd.received-data","log_level":1,"data":{"data":"       cgroup is already mounted on /sys/fs/cgroup/systemd\n       cgroup is already mounted on /sys/fs/cgroup/cpuset\n","path":"/tmp/cgroups-1/cpu","session":"7.1","type":"cpu"}}
[o][guardian] {"timestamp":"1445845659.624815464","source":"guardian","message":"guardian.setup-cgroup.mount-cgroup-cmd.received-data","log_level":1,"data":{"data":"       cgroup is already mounted on /sys/fs/cgroup/cpu,cpuacct\n       cgroup is already mounted on /sys/fs/cgroup/memory\n       cgroup is already mounted on /sys/fs/cgroup/devices\n       cgroup is already mounted on /sys/fs/cgroup/freezer\n       cgroup is already mounted on /sys/fs/cgroup/net_cls\n       cgroup is already mounted on /sys/fs/cgroup/blkio\n       cgroup is already mounted on /sys/fs/cgroup/perf_event\n       cgroup is already mounted on /sys/fs/cgroup/hugetlb\n       cgroup is already mounted on /tmp/cgroups-1\n","path":"/tmp/cgroups-1/cpu","session":"7.1","type":"cpu"}}
[o][guardian] {"timestamp":"1445845659.624980450","source":"guardian","message":"guardian.runner.command.failed","log_level":2,"data":{"argv":["mount","-n","-t","cgroup","-o","cpu","cgroup","/tmp/cgroups-1/cpu"],"error":"exit status 32","exit-status":32,"session":"2.4","stderr":"mount: cgroup is already mounted or /tmp/cgroups-1/cpu busy\n       cgroup is already mounted on /sys/fs/cgroup/systemd\n       cgroup is already mounted on /sys/fs/cgroup/cpuset\n       cgroup is already mounted on /sys/fs/cgroup/cpu,cpuacct\n       cgroup is already mounted on /sys/fs/cgroup/memory\n       cgroup is already mounted on /sys/fs/cgroup/devices\n       cgroup is already mounted on /sys/fs/cgroup/freezer\n       cgroup is already mounted on /sys/fs/cgroup/net_cls\n       cgroup is already mounted on /sys/fs/cgroup/blkio\n       cgroup is already mounted on /sys/fs/cgroup/perf_event\n       cgroup is already mounted on /sys/fs/cgroup/hugetlb\n       cgroup is already mounted on /tmp/cgroups-1\n","stdout":"","took":"1.713413ms"}}
[o][guardian] {"timestamp":"1445845659.625034809","source":"guardian","message":"guardian.setup-cgroup.mount-cgroup-failed","log_level":2,"data":{"error":"exit status 32","path":"/tmp/cgroups-1/cpu","session":"7","type":"cpu"}}
[o][guardian] {"timestamp":"1445845659.625054836","source":"guardian","message":"guardian.setup-cgroup.finished","log_level":1,"data":{"path":"/tmp/cgroups-1/cpu","session":"7","type":"cpu"}}
[o][guardian] {"timestamp":"1445845659.625111818","source":"guardian","message":"guardian.failed-to-start-server","log_level":3,"data":{"error":"exit status 32","trace":"goroutine 1 [running]:\ngithub.com/pivotal-golang/lager.(*logger).Fatal(0xc8200f60c0, 0x940ef0, 0x16, 0x7f716ab35f08, 0xc8200fc3e0, 0x0, 0x0, 0x0)\n\t/home/tony/Documents/go/src/github.com/pivotal-golang/lager/logger.go:131 +0xc5\nmain.main()\n\t/home/tony/Documents/go/src/github.com/cloudfoundry-incubator/guardian/cmd/guardian/main.go:228 +0x8c2\n"}}
[e][guardian] panic: exit status 32
[e][guardian] 
[e][guardian] goroutine 1 [running]:
[e][guardian] github.com/pivotal-golang/lager.(*logger).Fatal(0xc8200f60c0, 0x940ef0, 0x16, 0x7f716ab35f08, 0xc8200fc3e0, 0x0, 0x0, 0x0)
[e][guardian] 	/home/tony/Documents/go/src/github.com/pivotal-golang/lager/logger.go:152 +0x698
[e][guardian] main.main()
[e][guardian] 	/home/tony/Documents/go/src/github.com/cloudfoundry-incubator/guardian/cmd/guardian/main.go:228 +0x8c2
[e][guardian] 
[e][guardian] goroutine 17 [syscall, locked to thread]:
[e][guardian] runtime.goexit()
[e][guardian] 	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
[e][guardian] 
[e][guardian] goroutine 5 [syscall]:
[e][guardian] os/signal.loop()
[e][guardian] 	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
[e][guardian] created by os/signal.init.1
[e][guardian] 	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
• Failure in Spec Setup (BeforeEach) [3.639 seconds]
Net
/home/tony/Documents/go/src/github.com/cloudfoundry-incubator/guardian/gqt/net_test.go:120
  should have a (dynamically assigned) IP address [BeforeEach]
  /home/tony/Documents/go/src/github.com/cloudfoundry-incubator/guardian/gqt/net_test.go:63

  Expected error:
      <*url.Error | 0xc820212b10>: {
          Op: "Post",
          URL: "http://api/containers",
          Err: {
              Op: "dial",
              Net: "unix",
              Source: nil,
              Addr: {
                  Name: "/tmp/garden_1.sock",
                  Net: "unix",
              },
              Err: {Syscall: "connect", Err: 0x2},
          },
      }
      Post http://api/containers: dial unix /tmp/garden_1.sock: connect: no such file or directory
  not to have occurred

  /home/tony/Documents/go/src/github.com/cloudfoundry-incubator/guardian/gqt/net_test.go:29
------------------------------


Summarizing 1 Failure:

[Fail] Net [BeforeEach] should have a (dynamically assigned) IP address 
/home/tony/Documents/go/src/github.com/cloudfoundry-incubator/guardian/gqt/net_test.go:29

Ran 1 of 1 Specs in 3.639 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped --- FAIL: TestGqt (3.64s)
FAIL

Ginkgo ran 1 suite in 5.036839752s
Test Suite Failed
```

even though I run these test from scratch, I get this error, I don't know why `cgroup is already mounter`. 
If i run this command: `cat /proc/mounts | grep cgroup`, I will get such output:
```
tmpfs /sys/fs/cgroup tmpfs rw,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,nosuid,nodev,noexec,relatime,net_cls 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /tmp/cgroups-1 tmpfs rw,seclabel,relatime,mode=755 0 0
```
I did try to run this command: `umount /tmp/cgroup-1`, but useless. I am wondering how can I run this test case correctly.

**Comment by julz** [comment]
I think I see what's happening. We all develop on mac, so we only really run these linux-only tests inside [concourse builds](http://github.com/concourse/concourse). Concourse runs builds inside garden-linux containers, and these containers don't automatically mount any cgroups, but I think you're running the tests on a real linux host which already has cgroups mounted (probably because it's a modern linux with systemd enabled?). 

The workaround is to run these tests using concourse like we do (follow the instructions on the [concourse repo](http://github.com/concourse/concourse) to set up a local `concourse/lite` environment and then you can use `./script/test` inside [guardian-release](http://github.com/cloudfoundry-incubator/guardian-release) to do this). The real solution, of course, is we should make sure these tests cope with running inside an environment that already has cgroups mounted. I created a [story here](https://www.pivotaltracker.com/story/show/106740184) to do this.

Thanks again!

**Comment by AdoHe** [comment]
@julz Thanks very much. I will try that on my MBP.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#106740184](https://www.pivotaltracker.com/story/show/106740184) GQT tests should work when run on 'real' linux (not a container)


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by svett** [comment]
@AdoHe We fixed the tests. You should install aufs in order to run the tests as well. I updated the [README](https://github.com/cloudfoundry-incubator/guardian-release/blob/master/README.md) to illustrate exact steps.
